[package]
name = "simx"
version = "1.0.0"
edition = "2021"

[dependencies]
# 彩色控制台输出依赖
color-string = "0.1.6"
# 提供安全初始化全局变量方法
once_cell = "1.19.0"
# toml配置解析依赖
toml = "0.8.12"
# 序列化/反序列化
serde = { version = "1.0", features = ["derive"] }
# 序列化/反序列化
serde_derive = "1.0.197"
# 引擎默认数据库依赖（sqlite）
rusqlite = { version = "0.31.0", features = ["bundled"] }
# rust api框架
rocket = "^0.5.0"
# 异步运行时
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
# json解析依赖
serde_json = "1.0.115"
# 日志包
log = "0.4.21"
# 全局变量控制
lazy_static = "1.4.0"
# 用于获取时间
chrono = "0.4.38"
# 用于发起请求（Get/Post等）
reqwest = { version = "0.10", features = ["json"] }
# 异步处理
futures = "0.3.30"
