[workspace]
resolver = "2"

members = [
    # 共用部分，simx项目中的插件均引用此模块
    "common",
    # 核心扩展插件，包含大量的引擎节点handle
    "handler",
    # 引擎主体
    "kernel",
]

[profile.release]
# panic后让os清理
# 可以减少可执行文件的大小
panic = "abort"

# 调试模式
[profile.dev]
panic = "unwind"