workspace = { members = ["src/core/flow/handler/endpoint/endpoint_network"] }
[package]
name = "simx"
version = "0.1.0"
edition = "2021"

[dependencies]
# 彩色控制台输出依赖
color-string = "0.1.6"
once_cell = "1.19.0"
# toml配置解析依赖
toml = "0.8.12"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.197"
# 引擎默认数据库
rusqlite = { version = "0.31.0", features = ["bundled"] }
# rust api框架
rocket = "^0.5.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
# json解析依赖
serde_json = "1.0.115"
# 日志包
log = "0.4.21"
lazy_static = "1.4.0"
# 用于获取时间
chrono = "0.4.38"
