[package]
name = "simx"
version = "0.1.0"
edition = "2021"

[dependencies]
color-string = "0.1.6"
once_cell = "1.19.0"
toml = "0.8.12"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.197"
rusqlite = { version = "0.31.0", features = ["bundled"] }
rocket = "^0.5.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
