[project]
# 项目名称
name = "demo"
# 项目版本
version = "0.1.1"
# 作者
author = "Noah Jones"
# 项目描述
description = "A demo project"
# 流目录
flows = "services"
# 配置目录
config = "config"

# 环境要求
[requirements]
engine = ">=0.1.0"

# 依赖列表
[dependencies]
simx-restful = "0.1.1"
simx-mysql8 = "0.1.0"
simx-math = "0.1.0"