[extension]
# 是否允许加载非系统默认的插件
enabled = true
# 自动加载时机（soon：系统启动后空闲时 | used: 使用到此插件时 | always: 始终加载）
load-time = "always"
# 允许的类型，可选jar、dll、so
allow-type = ["jar", "dll", "so", ]

# 流节点仓库
[warehouse]
# 远程handler仓库，默认为
url = "https://lib.tineaine.cn"
port = 9999
# 运行流程过程中，如果缺少依赖的节点，允许simx自动前往仓库拉取
auto-pull = true