[net]
# 是否启动http 监听
# 如果没有启用，系统将在运行完默认流程和脚本后自动退出，除非开启了socket的监听
rest_enable_listener = true
# 监听地址
rest_listener_address = "127.0.0.1"
# 监听端口
rest_listener_port = 9898
# 工作线程数，数量越多，理论性能越高，占用资源越多
rest_listener_worker = 5
# http temp临时目录所在位置
rest_listener_temp_path = "tmp/web"
# 是否启动Socket 监听
socket_enable_listener = false
