[engine]
run_init_script = false
run_init_flow = true
# 运行插件的初始化方法，一般不建议关闭
run_init_extensions_func = true
# 允许插件加载配置文件
allow_load_extension_config = true
extensions_init_list = ["engine-handler", "engine_common"]
auto_refresh_local_data = true
ext_path = "ext"
shell_log_level = "debug"
file_log_level = "info"
# 开启历史流日志（这个日志默认开启，但不会包含数据）
# 日志数据需要使用 Glue 业务管理台查看（二进制数据）
enable_history_log = true
# 历史日志中包含数据（默认false，开启后可以在日志中记录节点对数据的一切处理，包括处理前、后的数据快照，此配置会占用大量的内存，并严重拖慢流运行速度，生成巨大的日志，仅在调试时开启）
enable_data_in_history_log = false

missing_plugin_action = "warn"
missing_default_handel_action = "warn"
# 实例间通信方式
# 这里其实一直很纠结，如果真的实现了共享内存，很难安全的进行使用，暂时搁置吧
# share-memory: 使用共享内存（速度快，占用资源少，可执行部分控制操作）
# rustful: 使用rustful接口通信（宿主必须作为serve运行，可执行所有控制操作）
# id-file: 通过实例的描述文件通信（速度很慢，根据文件交换互相信息，不能执行控制操作）
instance_communication_type = "share-memory"
# 引擎执行策略：
# 对于项目而言，会无视此处的配置，默认就是阻塞等待
# once: 默认策略，不会阻塞，执行完成默认流程或传入流程后直接退出
# serve: 阻塞，执行完成或传入流程后阻塞，需要用户手动结束或通过线程/api结束
run_strategy = "once"
# 蓝图多入口并行，如果蓝图有多个入口，并行执行，默认为true
blueprint_multi_entry_parallel = true
# 蓝图多下游并行，如果蓝图节点有多个下游，并行执行，默认为false
blueprint_multi_downstream_parallel = false

# 蓝图最大执行循环，防止各种原因引起的死循环
# 此配置含义是，蓝图最多执行（ blueprint_max_loop * 蓝图节点数 ）次跳转，如果超过x次，则退出
# 默认5，-1则不限制（非常不建议，特别是goto之类的功能很容易引起死循环）
blueprint_max_loop_multiple = 5

# 最大内存缓存容量（默认1GB）
# 缓存flow文件到内存中，如果为0，则不缓存
# 单位：B、KB、MB、GB、TB
max_cache_size = "100MB"

# 缓存权重依据
# usage: 根据使用量总计（哪个流用的多，优先存储在内存中，目前仅实现这种方式）
# usage-last: 优先缓存最近使用的（最近使用较多的）
# size-s: 优先缓存小文件
# size-l: 优先缓存大文件
cache_weight_by = "usage"

[net]
rest_listener_port = 9899

[env]
python_path = "python"
enable_python_script = true
enable_shell_script = true
enable_batch_script = true
enable_powershell_script = true
enable_shell_script_in_mac = true
enable_shell_script_in_linux = true