[engine]
run_init_script = false
run_init_flow = false
# 运行插件的初始化方法，一般不建议关闭
run_init_extensions_func = true
# 允许插件加载配置文件
allow_load_extension_config = true
extensions_init_list = ["engine-handler", "engine_common"]
auto_refresh_local_data = true
ext_path = "ext"
shell_log_level = "info"
file_log_level = "info"
missing_plugin_action = "warn"
missing_default_handel_action = "warn"
# 实例间通信方式
# share-memory: 使用共享内存（速度快，占用资源少，可执行部分控制操作）
# rustful: 使用rustful接口通信（宿主必须作为serve运行，可执行所有控制操作）
# id-file: 通过实例的描述文件通信（速度很慢，根据文件交换互相信息，不能执行控制操作）
instance_communication_type = "share-memory"
# 引擎执行策略：
# once: 默认策略，不会阻塞，执行完成默认流程或传入流程后直接退出
# serve: 阻塞，执行完成或传入流程后阻塞，需要用户手动结束或通过线程/api结束
run_strategy= "serve"

[net]
rest_listener_port = 9899

[env]
python_path = "python"
enable_python_script = true
enable_shell_script = true
enable_batch_script = true
enable_powershell_script = true
enable_shell_script_in_mac = true
enable_shell_script_in_linux = true