[engine]
run_init_script = true
run_init_flow = false
auto_refresh_local_data = true
ext_path = "D:\\Code\\simx-core\\release"
shell_log_level = "debug"
file_log_level = "info"
missing_plugin_action = "warn"
missing_default_handel_action = "warn"

[net]
rest_listener_port = 9899

[env]
enable_python_script = true
enable_shell_script = true
enable_batch_script = true
enable_powershell_script = false
enable_shell_script_in_mac = true
enable_shell_script_in_linux = true
python_path = "python"