project_name: Transfer
author: 'Charlie'
create_date: '2024-05-06 09:55:55'
modify_date: '2024-05-06 09:55:55'
version: 1.0.0
engine: 1.0.0
require:
  - "com.tineaine.simx(1.0.0)"
  - "com.tineaine.proc(1.0.0)"
flow_async: true
exception: skip
flow:
  - flow/auth/user.flow
  - flow/auth/info.flow
  - flow/auth/dept.flow
